#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT
ctags --tag-relative -Rf$dir/tags.$$ --exclude=.git --languages=-javascript,sql
mv $dir/tags.$$ $dir/tags
